version: "3.8"

services:
  aspnet:
    build: .
    image: aspnet_webapi
    container_name: webapi_mssql
    ports:
      - "8080:8080"
    extra_hosts:
      - "localhost:172.18.0.2"
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    volumes:
      - .docker/mssql:/var/opt/mssql
